all: robo castelo bonecoDeNeve

robo: 
	gcc robo.c -lglut -lGL -lGLU -lm -o robo.out
clean:
	rm -rf *.o *.out
castelo:
	gcc castelo.c -lglut -lGL -lGLU -lm -o castelo.out
bonecoDeNeve:
	gcc bonecoDeNeve.c -lglut -lGL -lGLU -lm -o bonecoDeNeve.out
